### ISSUE TITLE
To-do 20161208-20161213

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2015ori#24]
- [ ] Go through Marcel's final comments
- [ ] Update surfdrive files
- [ ] Update qualtrics download files (same files as above)

Reply here if I forgot something.

**Comment by JanGVoelkel** [comment]
I updated all things in the qualtrics and github (added to pull request). Please take a look in qualtrics but I think the solution is quite nice.

The only thing is that we may want to add a third time window per day?
